b2bevents description updates
adobe/xdm pull request #1162
Opened 2021-02-19 00:28 UTC by prabhum2

Please link to the issue #…

2021-02-19 23:26 UTC, peichiang requested changes

2021-02-19 23:26 UTC, peichiang commented on components/mixins/experience-event/events/scorechanged.schema.json
> +                  "description": "Friendly name of the lead score attribute."
Friendly name of the lead score attribute. => Name of the lead score attribute.

2021-02-19 23:26 UTC, peichiang commented on components/mixins/experience-event/events/statusincampaignprogressionchanged.schema.json
> +                  "description": "Friendly name of the lead's new status in the campaign."
Friendly name of the lead’s new status in the campaign. => Name of the lead’s new status in the campaign.

2021-02-19 23:26 UTC, peichiang commented on components/mixins/experience-event/events/visit-webpage.schema.json
>                  "xdm:queryParamaters": {
xdm:queryParamaters =>xdm:queryParameters

2021-02-19 23:26 UTC, peichiang commented on components/mixins/experience-event/events/visit-webpage.schema.json
>                    "title": "Query Paramaters",
“title”: “Query Paramaters” => “title”: “Query Parameters”

2021-02-19 23:26 UTC, peichiang commented on components/mixins/experience-event/events/visit-webpage.schema.json
> +                  "description": "Query Paramters used for the web page. This is normally the value of a string after ? in the url."
Query Paramters used for the web?page. This is normally the value of a string after `?` in the url. => Query Parameters used for the webpage. This is normally the value of a string after `?` in the url.

2021-02-22 19:06 UTC, prabhum2 commented on components/mixins/experience-event/events/emailbounced.schema.json
> +              "description": "Friendly name of the email asset."
we typically use friendly in any non standard name description

2021-02-22 19:06 UTC, prabhum2 commented on components/mixins/experience-event/events/emailbounced.schema.json
> +              "description": "Friendly name of the test variant of the email asset ."
same as above

2021-02-22 19:06 UTC, prabhum2 commented on components/mixins/experience-event/events/emailbouncedsoft.schema.json
> +              "description": "Friendly name of the email asset."
same as above

2021-02-22 20:58 UTC, mjasrotia approved these changes

2021-02-23 02:30 UTC, peichiang reviewed
1. Many of the “Friendly name” usage instead of "Name" due to convention. Waiting for Liz to confirm.
2. We used “webpage” in most places and “web page” in some places listed below. Should we be consistent?

2021-02-26 23:34 UTC, peichiang approved these changes

2021-03-02 03:52 UTC, merged