add scoping info to commerce.schema.json
adobe/xdm pull request #1738
Opened 2023-06-01 13:13 UTC by websterlove

[https://jira.corp.adobe.com/browse/SEG-828](https://jira.corp.adobe.com/browse/SEG-828)

Commerce scoping info allows merchants to differentiate where each of their events took place across multiple store views/stores/websites within an Adobe Commerce environment

2023-06-01 13:23 UTC, websterlove commented
@aniham @suranjanabasu Please check if you think the fields I've added here match your understanding of what we need to capture. In particular, I'd like to make sure the field names and descriptions are accurate and clear.

2023-06-02 16:04 UTC, websterlove commented
After further investigation I'm told that both environment ID and environment name are unique per merchant. Given that, I'd prefer to use environment name, since it's more human-readable. But it looks like Order Service currently only includes env ID (not sure about the data available to storefront events - Ani?). My proposal is: for now, stick with env ID, to get implementation done more quickly, but add env name later once we can make that data also available

2023-06-03 13:06 UTC, aniham requested changes
@websterlove sorry for not clarifying earlier. i listed out the correct names for the fields as they are used by commerce to uniquely identify a client

to your question on environment name vs id - it should be id which is the unique identifier

hope this helps!!

2023-06-03 13:06 UTC, aniham commented on components/datatypes/commercescope.example.1.json
> +  "xdm:environment": "27a15179-5545-4d23-e654-1b4ac0b42bd3",
should be `environmentId`

2023-06-03 13:06 UTC, aniham commented on components/datatypes/commercescope.example.1.json
> +  "xdm:website": "base",
should be `websiteCode`

2023-06-03 13:06 UTC, aniham commented on components/datatypes/commercescope.example.1.json
> +  "xdm:store": "main_website_store",
should be `storeCode`

2023-06-03 13:06 UTC, aniham commented on components/datatypes/commercescope.example.1.json
> +  "xdm:storeView": "default"
should be `storeViewCode`

2023-06-03 13:06 UTC, aniham commented on components/datatypes/commercescope.schema.json
> +        }
`environmentId`, `websiteCode`, `storeCode`, `storeViewCode`

2023-06-09 22:02 UTC, aniham approved these changes

2023-06-19 17:32 UTC, mjasrotia commented
@websterlove , I am closing this as this was taken care of in the below PR
\https://github.com/adobe/xdm/pull/1747

2023-06-19 17:32 UTC, closed without merging